#pragma once
#include <cinttypes>
#include "Instance/Instance.h"
#include "Input/KeyCode.h"
#include "Math/Vector3.h"
#include "Input.generated.h"

enum class InputState {
	Begin,
	Change,
	End,
};

enum class InputType {
	Keyboard,
	Mouse,
	Touch
};

class [[reflect()]] Input : public Instance, BaseInstance<Input> {
	REFLECTION()
public:
	Input(Engine* engine) : Instance(engine) {}

	[[reflect()]]
	[[summary("The device identifier that produced this input.")]]
	EngineUUID DeviceId;

	[[reflect()]] 
	[[summary("The current state of this input. Input objects exist for the full lifecycle of the input (Begin, Change..., End)")]]
	InputState State;

	[[reflect()]]
	[[summary("If the input was generated by a keyboard or mouse, this represents which key or mouse button was responsible.")]]
	KeyCode Key;

	[[reflect()]]
	[[summary("The type of input that generated this event.")]]
	InputType Type;

	[[reflect()]] 
	[[summary("The position of the input. For mouse inputs, this is the cursor position. For touch inputs, this is the position of the touch and Z represents the touch pressure if hardware allows.")]]
	Math::Vector3<double> Position;

	[[reflect()]]
	[[summary("The change in position since the last state change. For mouse inputs, this is the change in cursor position (even if the cursor is locked). For scroll wheel events, the Z component represents the amount scrolled.")]]
	Math::Vector3<double> Delta;

	void SetPosition(const Math::Vector3<double>& position);
	void SetDelta(const Math::Vector3<double>& delta);
	void SetState(InputState state);
};

REFLECTION_END()